sudo: required
dist: trusty
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    secure: IRE99tIJ3brgytOp9FZw9fYoyHwZUb1hKDBHOP36CjBPG29XI7jtDZZZau16tA/GJ0H0pg+kCW1i17/VeedE+DaaVOk/U6ndWFbf+QZWXjKS8pzZfSbKmq13mhz5cvovSsCrr8nS/DNrZj9yP1moXtfpetZCAf8vS/VsDDFX6/kZnEwsNXz5liEKhNFJRZSaZ5u8kJAZnRycbnD5MqblhP0xAa4YvksP84+0tQNn1GmF/zGJEs3pd5Yi7BHLyRhraYPXfSkVWQYjklXwMjT9BDYtn6+Yj3nNWtFSy6Jv2Gp75lTqxXcDoe2ORPb7sfGifp1v4Txd8gi5QgaXOX9UableFR/muRyM4SADKMBiXiADtSqmiXuxqTVYO9NtCRSkpCoE607sptqOc93mgcHQbeWK/sthg0XPr/Gkg13d/sYcSWJ1cCuW5ntc7fb29SqIaCzpDcK4L3G5BSchbiEx14ucib8lvzWgip0W2GgYm+tN8qngCBPwE0RdnjiQXJruL8fFIpVFPUh+Ri7nIrVd6I/ZNmuPfKEhQU3lt6/Tgn/2JZGvNR8L4h1nKiID+27v6yw/Zg93oVXSoKTFbGtH2XePuvXNTpoNAtc4aqMkr6/JccGHwOXfRY4d3PQw84ZVfGysRXHXLfXiomTqLwuKSX3dZ7tpNkZn3Quu583dQss=
install: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml"
env:
  global:
  - CEDAR_HOST=metadatacenter.orgx
  - CEDAR_ADMIN_USER_API_KEY=1234
  - CEDAR_NCBI_SRA_FTP_HOST=ftpHost
  - CEDAR_NCBI_SRA_FTP_USER=ftpUser
  - CEDAR_NCBI_SRA_FTP_PASSWORD=ftpPassword
  - CEDAR_NCBI_SRA_FTP_DIRECTORY=ftpDirectory
  - CEDAR_IMMPORT_SUBMISSION_USER=submissionUser
  - CEDAR_IMMPORT_SUBMISSION_PASSWORD=submissionPassword
  - CEDAR_NEO4J_HOST=127.0.0.1
  - CEDAR_NEO4J_BOLT_PORT=7687
  - CEDAR_NEO4J_USER_NAME=neo4j
  - CEDAR_NEO4J_USER_PASSWORD=neo4j
  - CEDAR_MONGO_APP_USER_NAME=cedarUser
  - CEDAR_MONGO_APP_USER_PASSWORD=password
  - CEDAR_REDIS_PERSISTENT_HOST=127.0.0.1
  - CEDAR_REDIS_PERSISTENT_PORT=6379
  - CEDAR_SUBMISSION_HTTP_PORT=9010
  - CEDAR_SUBMISSION_ADMIN_PORT=9110
  - CEDAR_SUBMISSION_STOP_PORT=9210
  - CEDAR_MESSAGING_HTTP_PORT=9012
  - secure: hZcWosignMQRfxUtuK/ufsdNlUoKBsb8DvuZD1eIj3s7dgH5TtjC+DkRvK3anQtBEe1eq+zAkwsv+Mvkwx1lfzXLXOVuRff2NAoAawpYU4PurBBPz7zl6IemjGIKXIsH+1Gg40afha8f9kWU8XNbq33p6zoyfNowAOh1Z2f3r95N5+PKJLoOqvWoFr5uf3SbyeKvKUZErWQ7PICsNyTUTc1qfpHPkFDW8zhnsROlFaSqx1+5we0d7vcq7195iFxkmurMKIyLiq7aCKmAH5t4BGtMkNXWAfj29za6js4l2VWddcybm7l4rLVjGPrAMkOC2+f8NftcJMXCMfav+IVRuyjd7rMbSspUoDvnJgIbaydPBTGN1dTwADiPoRgeIqkpqUXvM6n6HIz13lqUuHgsFASfWhWba0m9AbstRsKO12lBSRDSpj0AH/bEfKTmSLV0S3WslKDHPH5LW0QzoGr/1lAjxtjWi5iy1hsfzSLri4bzFpG3D7gk6us6wwvaTLQEl6z/5TjYHmZNAcwUTz4fLGMm6ulMG1Ep7TKSc8T9H5GmYEGYwIt3pM0T9JMzOQoTNwRFvpTc3GYpLoN+qtMQtwx4tRRYzlFEOipO6DFcfVcuTbCbtB6s5Di1caMFaa4pqTE2XAopTWtxd+DImAkDa0doDCaOj9yU109WWaAUsDs=
  - secure: drjzZPTLeUZIQSG2flsX4mXiSN/e1AMi84e7zuUhebE8uLi8PoEssPn4aqi5QzHY+ueK+2SylzAckvsrUJAv4tXzlwPhLZo3bDMz4ZFjsykynExJOKL+mkVEHogM2xpXROo76xajaDz+TykfwLQR/7IjULk5v7rQskP92QXHEZ9XDRfx64ewELml6Hjh4C9brOLWI/VbAMRbP2ahVsNVG4rhIIDJvhvhPDBK720tTcvI+np3KOvvP/j+oqKzX8d+Efth03Nkjl0a8fh7gk6UEH4KHAGAgasUkA/4FgdIiJpgCSa90VrjBnyR74XpO3kztUNO/ExsRJ/pdwIRaazeh0q8xJtqbwMv/tDu2mDLBov122qMZzX7ZWE0uya3ZWHVa/u8GQNqGGLyAjjq2Onqzl6mSZHBbH4HheXHxbyL24hIslsh38gZVWPnyQawoI4DaEzW8Y7Zf5A6xbckMhD+33CiHmsRhHPvkx+3d1gR1oStQky+J0cdOuSYv699HcXXhRoWGPsAkniiY5j98xnosIKrFgZQ1wwdUz4PekCQoiTJxAENi3I48QBTRbwsXaWiHkUisI1uXX3ERX4Pgb7YIe3UgRUVgTSh+0GURuWzNUVxyT7QVivSMmAy7ryn8miNi2KXzsX2kqLPDsKpwH3VooKETyQQjX5Dnjyaho5uwQY=
