sudo: required
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    secure: H9IzhdrqF6O+SS4gy/U1jL9WW4kvGFKW/PbTWLd11zI79oz3j+bTnX9E+Dev8ZigCMdd7BTanepE8kPruKT642MKIIhV5EArLLpSFiOXIZ4jmAlD8EoJ5xOf1+Z6cIW1TpkZSYp8GnZjlbRjUIQQvc5lXRcoiD26dz6MbvfWtZTcu1o+n+QGXDRjsg/XDNddAB3GEXXCZc+JJLBsGB+cQ5Ae0ph/rIVbRKByNSg86qrIYVd0D9OnxRXbahR3v+k3xcAFVXT6nrL6Jbw1IY8ARECVOxoxBPVeIJEaFKHor5cd3doapQ8IJjkT1aKb0XTtDXsutjLJdiV0opdeNDvdC8AUxQ8fFxGYS464o5wON//LsaQqLhyfat1ULZ/8y7+QH239FDOFnM/MuLD91OyK9wDK/HsA7n772srJRSDUMoBQvihf68/dDdsSZlSnjYyDMPxiKWCreFMnKCjiBrYvTKiDLpsQgUjz3M9t5PCSqw8Y7agKIRkfVnN6UHn48HY835ZvFDkJI4+/F+HCa9hkGyVxepXN1mnm30NBLcL3FSg9/51WhYPEw3V6izrO0qX/4pRyQswFiqkzOnJf6dA2csMkmayYGh2qkeOINi3EP4bJdURSHTGCb14FEwGnGyiMYS0b82FowyqugvqgmSXPmPL2S7ReztIn9BHv13DawHU=
install: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml"
env:
  global:
  - CEDAR_HOST=metadatacenter.orgx
  - CEDAR_ADMIN_USER_API_KEY=1234
  - CEDAR_NCBI_SRA_FTP_HOST=ftpHost
  - CEDAR_NCBI_SRA_FTP_USER=ftpUser
  - CEDAR_NCBI_SRA_FTP_PASSWORD=ftpPassword
  - CEDAR_NCBI_SRA_FTP_DIRECTORY=ftpDirectory
  - CEDAR_IMMPORT_SUBMISSION_USER=submissionUser
  - CEDAR_IMMPORT_SUBMISSION_PASSWORD=submissionPassword
  - CEDAR_NEO4J_HOST=127.0.0.1
  - CEDAR_NEO4J_BOLT_PORT=7687
  - CEDAR_NEO4J_USER_NAME=neo4j
  - CEDAR_NEO4J_USER_PASSWORD=neo4j
  - CEDAR_MONGO_APP_USER_NAME=cedarUser
  - CEDAR_MONGO_APP_USER_PASSWORD=password
  - CEDAR_REDIS_PERSISTENT_HOST=127.0.0.1
  - CEDAR_REDIS_PERSISTENT_PORT=6379
  - CEDAR_IMPEX_ADMIN_PORT=9108
  - CEDAR_IMPEX_HTTP_PORT=9008
  - CEDAR_IMPEX_STOP_PORT=9208
  - CEDAR_MESSAGING_HTTP_PORT=9012
  - secure: rspJZKDyluDeGrJykmqQDJwH7kBq+2fGAKQrmaGQUrCKg159C77HTRQIMz5b16KYt3QXHJLBDqR0JThjZr8jVEM8n6ef56XWmwOhTYl9gENLd08CcpRPlRlGPpNkUCPKE3sWoWQ5aIlhL1/CUAjWkZtcFGXPCM+IsccxM6p9HPs9IzEoqMLEcduGtEE0zuatFkOyYoAgVwCmH1mFmbzWTcnmYoC6FZuQ+5ZC4qhWh7HaqfAQ4uTblOQpf2kG5/wME7aYMe8zynMTNQQNf5+SbHHm2foVu5rOYVw06EX6KUC7HaSuxCwZyPMfQ2dVSUFLEmaBAoYW9aP6AJmNP9Wi6pGjbzaK7b2mOnHcIhXKrZet0CieFRgK7InY5p8ZpXT64+6axWCvmk50AoZp6qV2zwV+zlo04QXOYDqHPSk0sEhMzybpdBDh4s7YberciVKJyLdc4aEAmk1X2YHgJzfqMuRSQkoX8T2InlwZ9nkQdeKR7LzwXSZWLiMRVsyD6wtd+VO/56EPSyIFNflpx+NrydLLwlRWfonuxGb/i8qTe2GtX2LuDRK+YlA1oa03rztd8S23PYIDo4KRCz+SzZ/cv+MxZxXmTbpKLVA2WK3I6+ZQzXvhznEPDHVPyjwTjcZJ2JmaXUPVaJ+BPAFMYjT8E/Pe/v2LDJ3wVJ+Gnm3w70I=
  - secure: TtFks38AsFSG6mitrCY0u0mnQ0wqtbNCdJHjXmhZz2BmwndxKgO7cKdwoWc//wfHpL1kABk5vHsoohwvzSxdQBkkbf4eb8mB/mpnplEM7YCziL4BSQXOw0eqHFLXj0nK3Ojeg0A87oOAQ1caix1iPiJQsWhjtNFV5EGkZ1xvwf9lsJmAomgtzzANwgbl5RNVXBynB4ZWm7AkjzeD0O8IC653z6Af29aTnoKYXhMvwTMPjVRP7mw563+MmrNlVVB2VstvUW9Z3jHVlN9aKyDa2goK/tTpY1qIdYaaHvN7qpFeKVn2YUkQkjd55NoVSV4QctNRf8mziiEcz/hFgBalmOxx+O+WK4JchQ1ks6VPYuASbIxfktrG1aqkWUDXMTEAew11unkvTgdeBrTNwNB1ZL8ow2RJcJvnfaJP5TEojMXweumCeokOFl5cMM/lkn9gef0cg/buKvekEtbsv3zs6EGWE1tbbMgRbus7Fgl2Qh9Iqc9JBxEnmk6/EkeMXpJoZuP27dkn6oLeyqakqhHLD0PS1CWLVC/IbXm+PgI+zl8v/fgrFpWzINdP6yiXh8c05Bw0ZKNi4T4PJ18yIN6O6ow+SC2Wag3HUUoIRz1NhQhU1uM2WkbB5fJ0/M9l+uQ5jX2wy7dj0ZH6kBcBVxIcJuvrs3LhFeWj2PsfmaVjqU0=
