sudo: required
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    secure: H9IzhdrqF6O+SS4gy/U1jL9WW4kvGFKW/PbTWLd11zI79oz3j+bTnX9E+Dev8ZigCMdd7BTanepE8kPruKT642MKIIhV5EArLLpSFiOXIZ4jmAlD8EoJ5xOf1+Z6cIW1TpkZSYp8GnZjlbRjUIQQvc5lXRcoiD26dz6MbvfWtZTcu1o+n+QGXDRjsg/XDNddAB3GEXXCZc+JJLBsGB+cQ5Ae0ph/rIVbRKByNSg86qrIYVd0D9OnxRXbahR3v+k3xcAFVXT6nrL6Jbw1IY8ARECVOxoxBPVeIJEaFKHor5cd3doapQ8IJjkT1aKb0XTtDXsutjLJdiV0opdeNDvdC8AUxQ8fFxGYS464o5wON//LsaQqLhyfat1ULZ/8y7+QH239FDOFnM/MuLD91OyK9wDK/HsA7n772srJRSDUMoBQvihf68/dDdsSZlSnjYyDMPxiKWCreFMnKCjiBrYvTKiDLpsQgUjz3M9t5PCSqw8Y7agKIRkfVnN6UHn48HY835ZvFDkJI4+/F+HCa9hkGyVxepXN1mnm30NBLcL3FSg9/51WhYPEw3V6izrO0qX/4pRyQswFiqkzOnJf6dA2csMkmayYGh2qkeOINi3EP4bJdURSHTGCb14FEwGnGyiMYS0b82FowyqugvqgmSXPmPL2S7ReztIn9BHv13DawHU=
install: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml"
env:
  global:
  - CEDAR_HOST=metadatacenter.orgx
  - CEDAR_ADMIN_USER_API_KEY=1234
  - CEDAR_NEO4J_HOST=127.0.0.1
  - CEDAR_NEO4J_BOLT_PORT=7687
  - CEDAR_NEO4J_USER_NAME=neo4j
  - CEDAR_NEO4J_USER_PASSWORD=neo4j
  - CEDAR_MONGO_APP_USER_NAME=cedarUser
  - CEDAR_MONGO_APP_USER_PASSWORD=password
  - CEDAR_REDIS_PERSISTENT_HOST=127.0.0.1
  - CEDAR_REDIS_PERSISTENT_PORT=6379
  - CEDAR_IMPEX_ADMIN_PORT=9108
  - CEDAR_IMPEX_HTTP_PORT=9008
  - CEDAR_IMPEX_STOP_PORT=9208
  - CEDAR_MESSAGING_HTTP_PORT=9012
  - secure: ym800/x4WbBWpkafu869O3ua6uR5DYHS1JOp4a3Wads6hvAbNn81YyU6gN9hj9xZ3zIVNjUDlGB+f4d40Khu9P/+ZwBit7GHKKMdvfZwnXYTvpHZ0SEV1pykLlqwfjIP94+By5ad4lt3DTRciySP8Vnu3qGrNpsfYAKWr3dw4rC2hagX/YU9OIO2Jt8rfi5qfbXFrDDiExeUqixhbBLICKu3yQAWVamsmXQf4pJsLHekTC65xdwmTMFE88p+qi5Wqs7utqg6tkaTH1rLyepFXVfvQdrqIxGSFU0cyQGvT/7H2OvrBnS/GrV/twSPXM2F4L2oSXeMQAr6eQjZmsTk6dqiUNzIbOWl8zozpOK9NoTxYtYgk9xpkSjLdicY68N3BhfLPSHU/FSAp7AdARjtOtN6k98MfRiHBPe1aMZiJpL6q7ihLExhscxTjqbvFr4bzy9jP7aqoJ57c4p/R9iCiEW4FT+o07+/RDG61NCYLL8CUy/VFUr07MaiTJR+QtI7YwxkCwjEtcgDMqBBBrc8EACIoMh8aN/9ZLkrYwRQNJuGp4xVO/ADun6SXesILnBiYjcEcxu7QOS3d+pgV+lA4xZwVOMdhJTZK4ZFp1wy1As4lzcyqbcXAVsvA+HPe23MYFRjRmJE8jma/QeN4y91v2meeCzKnFcRLpC66Wvfaaw=
  - secure: uckHPikTTNCHU8Djf5mW5X/I1jkmXjfLS8qGrPLGeaZC6YUe18to2iJwBt2QNb47ToCBePzG86uP4L0nQFhbof9yi4WV++OsverVbpvKdPYru3HdCexomDFRxxvoOxgcaQjRkVkamyllqfNOMgo9/tpvuD//0y26H5vqCYYbopaR4KnF/f29JS56EbRWXQ7Tc8QbzH+8udm3M/lbusqw+cXqKrXd01eaXlpGB+OegDtt9TG5J7Dx7Nklv4aFWXAXD9n38fsKPG0o8umCmV+YiZNQpBxRCla2AP1/dGpaPUmQBqlIUyFHKvTyN5TnLFcQcw0wl4PdYWHeET/eEoKPPikOGuyZpIzOJyYJMx+nGMVvVcQheU30bpZL8RnNiHP4UGT5uvWgRXPNM7k1omBRsqR8eLAXdxhWiMyu8wKSh5n64BPwD0XYUjQYrxdlxXTyvAED1aQvdqT+JjDvi/y7sbj624tUZTVNMIYa9Bnuk1wSRUpMMik+cPxIHTOKnlOksO5rnccU9G0HfOkSIV6yB4tMpceObPuWKonjB2+sVoHRbED3SsL2FWdO5S5tlVwLmr0IZEgFuTUTA6y8kRvlrdGh9SKtem65rL7oIAa85LbsdXD5nDx8QxRV8X+nZXvOBdtWRzML7ItGtDrdk+LmyaOO6wqoY7iaHQynLh8LMFk=
