sudo: required
dist: trusty
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    secure: IRE99tIJ3brgytOp9FZw9fYoyHwZUb1hKDBHOP36CjBPG29XI7jtDZZZau16tA/GJ0H0pg+kCW1i17/VeedE+DaaVOk/U6ndWFbf+QZWXjKS8pzZfSbKmq13mhz5cvovSsCrr8nS/DNrZj9yP1moXtfpetZCAf8vS/VsDDFX6/kZnEwsNXz5liEKhNFJRZSaZ5u8kJAZnRycbnD5MqblhP0xAa4YvksP84+0tQNn1GmF/zGJEs3pd5Yi7BHLyRhraYPXfSkVWQYjklXwMjT9BDYtn6+Yj3nNWtFSy6Jv2Gp75lTqxXcDoe2ORPb7sfGifp1v4Txd8gi5QgaXOX9UableFR/muRyM4SADKMBiXiADtSqmiXuxqTVYO9NtCRSkpCoE607sptqOc93mgcHQbeWK/sthg0XPr/Gkg13d/sYcSWJ1cCuW5ntc7fb29SqIaCzpDcK4L3G5BSchbiEx14ucib8lvzWgip0W2GgYm+tN8qngCBPwE0RdnjiQXJruL8fFIpVFPUh+Ri7nIrVd6I/ZNmuPfKEhQU3lt6/Tgn/2JZGvNR8L4h1nKiID+27v6yw/Zg93oVXSoKTFbGtH2XePuvXNTpoNAtc4aqMkr6/JccGHwOXfRY4d3PQw84ZVfGysRXHXLfXiomTqLwuKSX3dZ7tpNkZn3Quu583dQss=
install: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml"
env:
  global:
  - CEDAR_HOST=metadatacenter.orgx
  - CEDAR_ADMIN_USER_API_KEY=1234
  - CEDAR_NCBI_SRA_FTP_HOST=ftpHost
  - CEDAR_NCBI_SRA_FTP_USER=ftpUser
  - CEDAR_NCBI_SRA_FTP_PASSWORD=ftpPassword
  - CEDAR_NCBI_SRA_FTP_DIRECTORY=ftpDirectory
  - CEDAR_IMMPORT_SUBMISSION_USER=submissionUser
  - CEDAR_IMMPORT_SUBMISSION_PASSWORD=submissionPassword
  - CEDAR_NEO4J_HOST=127.0.0.1
  - CEDAR_NEO4J_BOLT_PORT=7687
  - CEDAR_NEO4J_USER_NAME=neo4j
  - CEDAR_NEO4J_USER_PASSWORD=neo4j
  - CEDAR_MONGO_APP_USER_NAME=cedarUser
  - CEDAR_MONGO_APP_USER_PASSWORD=password
  - CEDAR_REDIS_PERSISTENT_HOST=127.0.0.1
  - CEDAR_REDIS_PERSISTENT_PORT=6379
  - CEDAR_SUBMISSION_HTTP_PORT=9010
  - CEDAR_SUBMISSION_ADMIN_PORT=9110
  - CEDAR_SUBMISSION_STOP_PORT=9210
  - CEDAR_MESSAGING_HTTP_PORT=9012
  - secure: j1PdYVUS0KYm5a4+QoQpET5pzzIZkxpWrJgmph/7i7tBGnnYZs0mTpZqVaSDBgwGxu3GmWzVAncRU6fxbbWJFu14eZexKou4Nwh+Tlrk65bEMWmW30EKtIbDOZtoSXw1AKa+vJU6343yxYdoXT7lUiav8l7slU+PUY6D+T1M4fWp1t9CWkE/SwIkmDbYXwIBNhHjspsw2W1Zd0OjqDm/6sOqYwDyUH3QHx8o0eGVH3DZIwYUUCxq684E4jl2tHyOueR4d3AE3SfGKw3dz+QGyXLkLrHHzhcu/uQbLVJn5AkKCUtumDRvVedFc6B0ktZWddU0QBZqCBln3WpMeOZ5RG4EkPA3eAbd7Ck+mWXfWOdiiyaJ57DP4iu/Wc+djZIKekXDVOCdsmHGx5vQ+UbKoiZSFo6QMnQvS2nqQ8RSpEGUxa8OFLLhqvX6UxEWHhRdNtifJfpco4gCk39cvfqH5gZsRi2RPXmBuX7w25BTCakq1fyeJqJXlUwuUBQCF2jEmXVst0/7Xet5n9YdA+AhSuhkZrOvfaVnmLJXrKr28YhyMkIB9NnNGilwlZR7K3zWKRssz9oA5Nshhs4HeWn67VzrUWkhFTX/GIQo+JUGwXGNcKJXHZb5wmzz7E0yvQU0a8ppBBPYP2rbWDx+8y4JkLDiqP1wFnLtMhr1+r3NG/E=
  - secure: IN57ilpsp9cMpVWxUOLB9K37usSUwHME+iPWEn9Qggn9zaZki7nRIJFmbzdOJig3kwCxoASKetn4STJV4/MYRFly+8KpkX+MJ9NXJcyDTk1NZ6TGfKXk4Jr4AkrblhbULFvrwBNDRdzPA2TWWwj5cp9GmnABHG0xnE2iTmCINJZq719eaqdbw1UQeVM51KI47OKHBGDORQ7pE1vnMEKR11UILaA94QO0N5kEndxFO0J3kZTk5glLmfliy+vS1wYY1R3s7G57JiXoSmL/YmHpqyH5Ybw4sRfGhqj2RGnLm4r35+p1kuoL8L2LCuswVByqfln3KxedQ00M0e+3nVnVEsVcxKPw7dbhobBBk11kp/Vmf4MzC1uHcG13EPEMK7SYtGX4ucqn1itCFx8MPrKcVGKEpGu+1IXNSDn/F5NeWPSguGkgYGAS87XLbXcust4AjRem1vw4AX8P3RZlyzej4egnfsZ49mK9yS14jlzKAtrWQLJlKy3yDeuKW7O3ehFNC/2chJgBgYfqf9VNZiB3yz7FoJ+65IhdUhklUjO7+FwNr6l+I00rabPVHS0oFzyRbITG7UTU3E6VH9fTOU9cGf5vaixMn6Fi7NFTFD5Nd8LbEvSqBw2dGKczqyYtJAj8SnDTSp328YPFqqRXdnW8+xT+Rd3w3gH0bUzFj0tqiiM=
