sudo: required
dist: trusty
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: xSIYhhwtzd+DV5oHEiT3ZVVCKsVlabQ7DMjx6xrq5XZtNBlsLSq6FhHJY37rbfI//6jv2PPZS2OUgNvhmDeiCrWbN6cIXZWkOVHcizfkKLvENLwnqvY+RU4gbwRvTfYEs+WPsl7iRRIahjKHGJHNuSnPSOwQ68eMr60WCSvakRX3ZOA0NgDW6v+MwUL9oTK25ArPhd0D98q5PVuvHmPTK/nc/CHjAJKIhrxqtgMb2PXYwX1YgEnHxbVarbVUqJsJ1Wi0t5PWvf6nLGPSp97f5mt7E68G+J+i18gGh9d/LWSpz8b1qOkxqB7xZwFOmp2Z0OyCNP0PeXmEKozdXMaEa5oi1eeIbot1VjjWrX9eL8b4JGLCR7cTLwZ1Zw7mZi3vTVSyqe9UEBZgGQAkixC0Y93TBRgstsv5/wDu2M4tIn68vKtCFRBnViJmau5UikYl0EukzzLB+LuJLZ2HgkhngwTxMdNIpXVDNRvMgRXMBfKYUmIneGNEAS2DJHlm6LDkGUpD4nBVJs1JJ07lRv/w9ithypLHgfOIWWtthr3JLuq0jvjJaVT91vxGcrUhLsXYnQbcy2l5yDXOLi+PA9UY0O/51m2t2hNojsZg2Eu0dNSipH7wZgGI7peO5hqAEx4F5IqlWBopSfHVd2M3CpyRp6yMMGbvZam1zE5RSg093F0=
install:
- sudo apt-get install -y ccrypt
- sudo apt-get install -y sharutils
- echo QA_AWS_KEY = $QA_AWS_KEY > info.txt
- ccencrypt info.txt -K $ENC_KEY
- uuencode -m info.txt.cpt info.txt.cpt
- "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=false clean deploy --settings .m2/travis-settings.xml"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=true clean --settings .m2/travis-settings.xml"
env:
  global:
  - CEDAR_HOST=metadatacenter.orgx
  - secure: BwQQ4KDAWSpXaGsARFHdA3i2wETLSSLqTY4MsM0cuv/7QrcKzCxLPzMB2Hn95/wJZBIIaZabhtaWdGpJ/Tfdnhqirn6+lQNaoIh9PEX/sM2ug9pTiMNkRm7nWT6BAoxGbp2DaP/bFN39mWLlrdZmJmUDOeAYaECllemSzCASb/skSdSciVk1YQRJ/m6TLb8IikqanFYcKnD5GEu8fSi/W28eafWt1M7yqqdBAFzr/+qbUgfTOs31uMAOPui9DUM7bIxJv4mhVS0kYYy3CiHgjampPNXk6UfyNGQM8HFtAjpV/GRZTnrv4QzXNeJFDs89cj4FqUqDimK6Y9TzClL4JH+xJC9fs0FDDuaK+1xD9Lum/A0vN0NYruvQbHPSv3ikUN65flotxwZfxF/NATNuXbIHLSplyOxXahEpwUMqxt7hILSLUJm6uGtmZRy8JUvf9UzSE8Tq/4g4yWf8K5Zsv+htlghPDIri6P2x0f0cp2k4R6FD8LjIcosoIIZPA7H088XvJA07YExdfr5CY/QA7crWyXt1Zdxnyv6QWNRRd3Nyb5G+bIEFM2pBAQmWWhA80j5N221t+Ujb0V8ia3s0PBuMFyNTpW+g2GptpI3k0st2YlWUlo0a37WMXilTSQPOGyi5iIo/EcHhuNpwIDewGWDXP6DSZ5sBkRBP7wyU/eA=
  - secure: lv2wuduFEv8E+VJpIkgtus3Xuw0arCDfNtvGTn3usWVB+PkL1CkPKYiU4wc3Yny5iPtr9Yux0jAM1P2GvZ0hpxo1PWu8Qn90mkZHau+OcYNAhD+Li6fS5yrUlOcnQnvAKgNg3+n/MfVmVSN7aN3+bojiJq9PEkAxe7CTEloPDbKnskVKqWuFo2UcWcKOWfjU8Fe/lk5lgZUc0v+xUV2x58yQ1rSMojNuNPIQv+TZVQwJSMXs6N8P0w4AxTDhKg7sp8VDjXKsH03nWVtOTj9QX92ViYH4KDnnTCgodAEWZr7LgSYPpTNk6z9BiAXKb06mMpViG5iYsWZV6R3heMq24bnl51uUmUasMKmiWW5ZA1GRQkg0g/jnL5MlDsdg2XzjpFkiIrBHBuzjRewF15kACPyFupricgR5Om3Bpb4SR3kownOl0arB90HGG5KSVODIi6GZVbadGnry9edgCFes8GVDU/52I9WxZtPuDs9sDgm/M/8130E4nh9sctd5dSklGh+vliQjwlmOUrasHrVbJU7bAp/StV2Href0T1ZGhWcKvCs5XJqAq4iPt1BK5qHollKYiWnon605mI4HksCIoeD0Z3rHaZ4GHFFNTetdzVS4UUDeDm3p7mp7O3iUqYvjJaJ4T1vd8EEhCb2bbouQXaJ9+q1WPlf1bZAuAAJZTew=
